title: Expert-Stats
site_name: 3CX Expert-Stats
description: Questions fréquemment posées
lang: fr

header:
  title: FAQ
  logo: 
  show_search: true
  search_placeholder: Rechercher...

footer:
  text: "© 2025 CX-Engine."
  links:
    - text: BlueRockTEL
      url: https://bluerocktel.com
      target: _blank
    - text: CX-Engine
      url: https://cx-engine.com
      target: _blank

theme:
  primary_color: "#3b82f6"
  primary_color_600: "#2563eb"
  primary_color_700: "#1d4ed8"

